---
name: OMC Docs
description: Publishes our API docs to our internal website at https://abc.omc.io
inputs:
  bucket:
    description: the s3 bucket to push to
    required: true
    default: api-docs.omc.io
  project_name:
    description: the folder to store these docs into
    required: true
  doc_path:
    description: the path to push to S3
    required: true
  doc_command:
    description: the command to run to generate docs
    required: true
    default: bin/doc
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  aws_default_region:
    required: false
    default: us-east-1
runs:
  using: 'node12'
  main: 'dist/index.js'
